### ISSUE TITLE
Uzantılar çalışmıyor

### ISSUE THREAD

**Issue by ardazeytin** [mskasal/teknoseyir-bildirim#1]
Ön izlemesi görülebilen yorumlar, beğenildiği yazan durumlar ve kullanıcı adlarına(bazıları çalışıyor @hsa mesela) tıkladığında sitede gerekli yere yönlendirmiyor. Tepki vermiyor.

**Comment by mskasal** [comment]
Linkler'e target= "_blank" eklenmeli.
