### ISSUE TITLE
Kullanıcılar İlgili bir post paylaştığında gelen bildirimler kayaboluyor

### ISSUE THREAD

**Issue by SevcanAlkan** [mskasal/teknoseyir-bildirim#12]
![screenshot 3](https://cloud.githubusercontent.com/assets/5174213/11424033/53a1b2e4-9452-11e5-9fa1-bd3216743315.png)

Bırdırımler hem ikişer defa geliyor hemde bir tanesine bakıntıktan sonra digerine bakmak için kapanan uygulama penceresini birdaha açtığımızda bildirimler yok olmuş oluyor.

**Comment by mskasal** [comment]
TS nin API kullanmak icin izledigi yol beni buna zorluyor. Eklenti her acildiginda TS ye gidip son post numarasini almam gerekiyor. Duplicate sorunu bilinen bir sorun, duzelttim aksam yayinlayacagim.
